import { ReactNode } from "react";

export const STICKERS = [
  // === ЭМОЦИИ ===
  { code: ":smile:", emoji: "😊", label: "Улыбка" },
  { code: ":laugh:", emoji: "😂", label: "Смех" },
  { code: ":joy:", emoji: "🤣", label: "Ржу" },
  { code: ":wink:", emoji: "😉", label: "Подмигивание" },
  { code: ":love:", emoji: "🥰", label: "Любовь" },
  { code: ":heart:", emoji: "❤️", label: "Сердце" },
  { code: ":kiss:", emoji: "😘", label: "Поцелуй" },
  { code: ":cool:", emoji: "😎", label: "Крутой" },
  { code: ":sunglasses:", emoji: "🕶️", label: "Очки" },
  { code: ":think:", emoji: "🤔", label: "Думаю" },
  { code: ":hmm:", emoji: "🧐", label: "Прищурился" },
  { code: ":neutral:", emoji: "😐", label: "Нейтрально" },
  { code: ":meh:", emoji: "😒", label: "Ме" },
  { code: ":sad:", emoji: "😔", label: "Грустно" },
  { code: ":cry:", emoji: "😭", label: "Плачу" },
  { code: ":sob:", emoji: "😢", label: "Слёзы" },
  { code: ":angry:", emoji: "😡", label: "Злость" },
  { code: ":rage:", emoji: "🤬", label: "Бешенство" },
  { code: ":mindblown:", emoji: "🤯", label: "Взрыв мозга" },
  { code: ":sleep:", emoji: "😴", label: "Сплю" },
  { code: ":drool:", emoji: "🤤", label: "Слюнки" },
  { code: ":sick:", emoji: "🤢", label: "Тошнит" },
  { code: ":sneeze:", emoji: "🤧", label: "Чих" },
  { code: ":mask:", emoji: "😷", label: "Маска" },
  { code: ":party:", emoji: "🥳", label: "Праздник" },

  // === ЖЕСТЫ ===
  { code: ":wave:", emoji: "👋", label: "Привет" },
  { code: ":clap:", emoji: "👏", label: "Аплодисменты" },
  { code: ":pray:", emoji: "🙏", label: "Молюсь" },
  { code: ":ok:", emoji: "👌", label: "Окей" },
  { code: ":victory:", emoji: "✌️", label: "Победа" },
  { code: ":cross:", emoji: "🤞", label: "На удачу" },
  { code: ":like:", emoji: "👍", label: "Лайк" },
  { code: ":dislike:", emoji: "👎", label: "Дизлайк" },
  { code: ":fist:", emoji: "✊", label: "Кулак" },
  { code: ":muscle:", emoji: "💪", label: "Сила" },
  { code: ":point_up:", emoji: "☝️", label: "Вверх" },
  { code: ":point_down:", emoji: "👇", label: "Вниз" },
  { code: ":middlefinger:", emoji: "🖕", label: "Фига" },
  { code: ":callme:", emoji: "🤙", label: "Позвони мне" },
  { code: ":raised_hands:", emoji: "🙌", label: "Ура" },
  { code: ":folded_hands:", emoji: "🫶", label: "Люблю" },

  // === ЖИВОТНЫЕ ===
  { code: ":cat:", emoji: "🐱", label: "Кот" },
  { code: ":dog:", emoji: "🐶", label: "Пёс" },
  { code: ":fox:", emoji: "🦊", label: "Лиса" },
  { code: ":wolf:", emoji: "🐺", label: "Волк" },
  { code: ":bear:", emoji: "🐻", label: "Медведь" },
  { code: ":panda:", emoji: "🐼", label: "Панда" },
  { code: ":tiger:", emoji: "🐯", label: "Тигр" },
  { code: ":lion:", emoji: "🦁", label: "Лев" },
  { code: ":frog:", emoji: "🐸", label: "Лягушка" },
  { code: ":monkey:", emoji: "🐵", label: "Обезьяна" },
  { code: ":see_no_evil:", emoji: "🙈", label: "Не вижу" },
  { code: ":hear_no_evil:", emoji: "🙉", label: "Не слышу" },
  { code: ":speak_no_evil:", emoji: "🙊", label: "Не скажу" },
  { code: ":pig:", emoji: "🐷", label: "Свинья" },
  { code: ":cow:", emoji: "🐮", label: "Корова" },
  { code: ":mouse:", emoji: "🐭", label: "Мышь" },
  { code: ":rabbit:", emoji: "🐰", label: "Кролик" },
  { code: ":unicorn:", emoji: "🦄", label: "Единорог" },
  { code: ":dragon:", emoji: "🐉", label: "Дракон" },
  { code: ":whale:", emoji: "🐋", label: "Кит" },
  { code: ":octopus:", emoji: "🐙", label: "Осьминог" },
  { code: ":butterfly:", emoji: "🦋", label: "Бабочка" },
  { code: ":bee:", emoji: "🐝", label: "Пчела" },
  { code: ":snail:", emoji: "🐌", label: "Улитка" },
  { code: ":turtle:", emoji: "🐢", label: "Черепаха" },

  // === ЕДА ===
  { code: ":pizza:", emoji: "🍕", label: "Пицца" },
  { code: ":burger:", emoji: "🍔", label: "Бургер" },
  { code: ":fries:", emoji: "🍟", label: "Картошка" },
  { code: ":hotdog:", emoji: "🌭", label: "Хотдог" },
  { code: ":taco:", emoji: "🌮", label: "Тако" },
  { code: ":sushi:", emoji: "🍣", label: "Суши" },
  { code: ":ramen:", emoji: "🍜", label: "Рамен" },
  { code: ":spaghetti:", emoji: "🍝", label: "Паста" },
  { code: ":curry:", emoji: "🍛", label: "Карри" },
  { code: ":salad:", emoji: "🥗", label: "Салат" },
  { code: ":cake:", emoji: "🎂", label: "Торт" },
  { code: ":donut:", emoji: "🍩", label: "Пончик" },
  { code: ":icecream:", emoji: "🍦", label: "Мороженое" },
  { code: ":cookie:", emoji: "🍪", label: "Печенье" },
  { code: ":chocolate:", emoji: "🍫", label: "Шоколад" },
  { code: ":popcorn:", emoji: "🍿", label: "Попкорн" },
  { code: ":coffee:", emoji: "☕", label: "Кофе" },
  { code: ":tea:", emoji: "🍵", label: "Чай" },
  { code: ":beer:", emoji: "🍺", label: "Пиво" },
  { code: ":wine:", emoji: "🍷", label: "Вино" },
  { code: ":cocktail:", emoji: "🍸", label: "Коктейль" },
  { code: ":milk:", emoji: "🥛", label: "Молоко" },
  { code: ":water:", emoji: "💧", label: "Вода" },

  // === ОБЪЕКТЫ ===
  { code: ":rocket:", emoji: "🚀", label: "Ракета" },
  { code: ":fire:", emoji: "🔥", label: "Огонь" },
  { code: ":bomb:", emoji: "💣", label: "Бомба" },
  { code: ":zap:", emoji: "⚡", label: "Молния" },
  { code: ":star:", emoji: "⭐", label: "Звезда" },
  { code: ":sparkles:", emoji: "✨", label: "Блеск" },
  { code: ":dizzy:", emoji: "💫", label: "Головокружение" },
  { code: ":boom:", emoji: "💥", label: "Взрыв" },
  { code: ":ghost:", emoji: "👻", label: "Призрак" },
  { code: ":skull:", emoji: "💀", label: "Череп" },
  { code: ":alien:", emoji: "👽", label: "Пришелец" },
  { code: ":robot:", emoji: "🤖", label: "Робот" },
  { code: ":poop:", emoji: "💩", label: "Какашка" },
  { code: ":clown:", emoji: "🤡", label: "Клоун" },
  { code: ":jack_o_lantern:", emoji: "🎃", label: "Тыква" },
  { code: ":gift:", emoji: "🎁", label: "Подарок" },
  { code: ":balloon:", emoji: "🎈", label: "Шарик" },
  { code: ":trophy:", emoji: "🏆", label: "Кубок" },
  { code: ":medal:", emoji: "🥇", label: "Медаль" },
  { code: ":crown:", emoji: "👑", label: "Корона" },
  { code: ":gem:", emoji: "💎", label: "Бриллиант" },
  { code: ":money:", emoji: "💰", label: "Деньги" },
  { code: ":dollar:", emoji: "💵", label: "Баксы" },
  { code: ":credit_card:", emoji: "💳", label: "Карта" },
  { code: ":phone:", emoji: "📱", label: "Телефон" },
  { code: ":computer:", emoji: "💻", label: "Ноутбук" },
  { code: ":keyboard:", emoji: "⌨️", label: "Клавиатура" },
  { code: ":mouse2:", emoji: "🖱️", label: "Мышка" },
  { code: ":camera:", emoji: "📷", label: "Фотоаппарат" },
  { code: ":bulb:", emoji: "💡", label: "Лампочка" },
  { code: ":battery:", emoji: "🔋", label: "Батарея" },
  { code: ":lock:", emoji: "🔒", label: "Замок" },
  { code: ":key:", emoji: "🔑", label: "Ключ" },
  { code: ":hammer:", emoji: "🔨", label: "Молоток" },
  { code: ":wrench:", emoji: "🔧", label: "Гаечный ключ" },
  { code: ":gun:", emoji: "🔫", label: "Пистолет" },
  { code: ":knife:", emoji: "🔪", label: "Нож" },
  { code: ":pill:", emoji: "💊", label: "Таблетка" },
  { code: ":syringe:", emoji: "💉", label: "Шприц" },
  { code: ":toilet:", emoji: "🚽", label: "Туалет" },
  { code: ":shower:", emoji: "🚿", label: "Душ" },
  { code: ":bathtub:", emoji: "🛁", label: "Ванна" },
  { code: ":bed:", emoji: "🛏️", label: "Кровать" },
  { code: ":door:", emoji: "🚪", label: "Дверь" },
  { code: ":mirror:", emoji: "🪞", label: "Зеркало" },
  { code: ":window:", emoji: "🪟", label: "Окно" },
  { code: ":clock:", emoji: "⏰", label: "Будильник" },
  { code: ":hourglass:", emoji: "⏳", label: "Песочные часы" },
  { code: ":watch:", emoji: "⌚", label: "Часы" },

  // === ПРИРОДА ===
  { code: ":sun:", emoji: "☀️", label: "Солнце" },
  { code: ":moon:", emoji: "🌙", label: "Луна" },
  { code: ":cloud:", emoji: "☁️", label: "Облако" },
  { code: ":rain:", emoji: "🌧️", label: "Дождь" },
  { code: ":snow:", emoji: "❄️", label: "Снег" },
  { code: ":wind:", emoji: "💨", label: "Ветер" },
  { code: ":rainbow:", emoji: "🌈", label: "Радуга" },
  { code: ":ocean:", emoji: "🌊", label: "Волна" },
  { code: ":mountain:", emoji: "⛰️", label: "Гора" },
  { code: ":volcano:", emoji: "🌋", label: "Вулкан" },
  { code: ":desert:", emoji: "🏜️", label: "Пустыня" },
  { code: ":beach:", emoji: "🏖️", label: "Пляж" },
  { code: ":island:", emoji: "🏝️", label: "Остров" },
  { code: ":camping:", emoji: "🏕️", label: "Кемпинг" },
  { code: ":tree:", emoji: "🌳", label: "Дерево" },
  { code: ":palm:", emoji: "🌴", label: "Пальма" },
  { code: ":cactus:", emoji: "🌵", label: "Кактус" },
  { code: ":herb:", emoji: "🌿", label: "Трава" },
  { code: ":flower:", emoji: "🌸", label: "Цветок" },
  { code: ":rose:", emoji: "🌹", label: "Роза" },
  { code: ":sunflower:", emoji: "🌻", label: "Подсолнух" },
  { code: ":maple:", emoji: "🍁", label: "Клён" },
  { code: ":fallen_leaf:", emoji: "🍂", label: "Лист" },
  { code: ":mushroom:", emoji: "🍄", label: "Гриб" },

  // === ТРАНСПОРТ ===
  { code: ":car:", emoji: "🚗", label: "Машина" },
  { code: ":taxi:", emoji: "🚕", label: "Такси" },
  { code: ":bus:", emoji: "🚌", label: "Автобус" },
  { code: ":train:", emoji: "🚆", label: "Поезд" },
  { code: ":metro:", emoji: "🚇", label: "Метро" },
  { code: ":tram:", emoji: "🚊", label: "Трамвай" },
  { code: ":airplane:", emoji: "✈️", label: "Самолёт" },
  { code: ":helicopter:", emoji: "🚁", label: "Вертолёт" },
  { code: ":ship:", emoji: "🚢", label: "Корабль" },
  { code: ":boat:", emoji: "⛵", label: "Лодка" },
  { code: ":bike:", emoji: "🚲", label: "Велосипед" },
  { code: ":motorcycle:", emoji: "🏍️", label: "Мотоцикл" },
  { code: ":ambulance:", emoji: "🚑", label: "Скорая" },
  { code: ":fire_engine:", emoji: "🚒", label: "Пожарная" },
  { code: ":police:", emoji: "🚓", label: "Полиция" },
  { code: ":taxi_top:", emoji: "🚖", label: "Такси сверху" },
  { code: ":fuel:", emoji: "⛽", label: "Бензин" },
  { code: ":traffic_light:", emoji: "🚦", label: "Светофор" },
  { code: ":construction:", emoji: "🚧", label: "Ремонт" },
  { code: ":anchor:", emoji: "⚓", label: "Якорь" },

  // === АКТИВНОСТИ / СПОРТ ===
  { code: ":soccer:", emoji: "⚽", label: "Футбол" },
  { code: ":basketball:", emoji: "🏀", label: "Баскетбол" },
  { code: ":tennis:", emoji: "🎾", label: "Теннис" },
  { code: ":baseball:", emoji: "⚾", label: "Бейсбол" },
  { code: ":volleyball:", emoji: "🏐", label: "Волейбол" },
  { code: ":rugby:", emoji: "🏉", label: "Регби" },
  { code: ":8ball:", emoji: "🎱", label: "Бильярд" },
  { code: ":golf:", emoji: "⛳", label: "Гольф" },
  { code: ":dart:", emoji: "🎯", label: "Дартс" },
  { code: ":bowling:", emoji: "🎳", label: "Боулинг" },
  { code: ":fishing:", emoji: "🎣", label: "Рыбалка" },
  { code: ":swim:", emoji: "🏊", label: "Плавание" },
  { code: ":run:", emoji: "🏃", label: "Бег" },
  { code: ":dance:", emoji: "💃", label: "Танец" },
  { code: ":man_dance:", emoji: "🕺", label: "Танец" },
  { code: ":gym:", emoji: "🏋️", label: "Тренажёрка" },
  { code: ":yoga:", emoji: "🧘", label: "Йога" },
  { code: ":game:", emoji: "🎮", label: "Игры" },
  { code: ":slot_machine:", emoji: "🎰", label: "Казино" },
  { code: ":dice:", emoji: "🎲", label: "Кости" },
  { code: ":puzzle:", emoji: "🧩", label: "Пазл" },
  { code: ":chess:", emoji: "♟️", label: "Шахматы" },
  { code: ":music:", emoji: "🎵", label: "Музыка" },
  { code: ":guitar:", emoji: "🎸", label: "Гитара" },
  { code: ":piano:", emoji: "🎹", label: "Пианино" },
  { code: ":drum:", emoji: "🥁", label: "Барабаны" },
  { code: ":trumpet:", emoji: "🎺", label: "Труба" },
  { code: ":violin:", emoji: "🎻", label: "Скрипка" },
  { code: ":microphone:", emoji: "🎤", label: "Микрофон" },
  { code: ":headphones:", emoji: "🎧", label: "Наушники" },
  { code: ":radio:", emoji: "📻", label: "Радио" },
  { code: ":tv:", emoji: "📺", label: "ТВ" },
  { code: ":film:", emoji: "🎬", label: "Кино" },
  { code: ":ticket:", emoji: "🎫", label: "Билет" },
  { code: ":art:", emoji: "🎨", label: "Искусство" },
  { code: ":books:", emoji: "📚", label: "Книги" },
  { code: ":newspaper:", emoji: "📰", label: "Газета" },

  // === СИМВОЛЫ / ЗНАКИ ===
  { code: ":check:", emoji: "✅", label: "Галочка" },
  { code: ":cross_mark:", emoji: "❌", label: "Крестик" },
  { code: ":question:", emoji: "❓", label: "Вопрос" },
  { code: ":exclamation:", emoji: "❗", label: "Восклицание" },
  { code: ":warning:", emoji: "⚠️", label: "Внимание" },
  { code: ":no_entry:", emoji: "⛔", label: "Стоп" },
  { code: ":prohibited:", emoji: "🚫", label: "Запрещено" },
  { code: ":recycle:", emoji: "♻️", label: "Переработка" },
  { code: ":infinity:", emoji: "♾️", label: "Бесконечность" },
  { code: ":trident:", emoji: "🔱", label: "Трезубец" },
  { code: ":fleur:", emoji: "⚜️", label: "Геральдика" },
  { code: ":peace:", emoji: "☮️", label: "Мир" },
  { code: ":cross:", emoji: "✝️", label: "Крест" },
  { code: ":star_of_david:", emoji: "✡️", label: "Давида" },
  { code: ":yin_yang:", emoji: "☯️", label: "Инь-янь" },
  { code: ":wheel_of_dharma:", emoji: "☸️", label: "Дхарма" },
  { code: ":atom:", emoji: "⚛️", label: "Атом" },
  { code: ":radioactive:", emoji: "☢️", label: "Радиация" },
  { code: ":biohazard:", emoji: "☣️", label: "Биоопасность" },
  { code: ":up:", emoji: "⬆️", label: "Вверх" },
  { code: ":down:", emoji: "⬇️", label: "Вниз" },
  { code: ":left:", emoji: "⬅️", label: "Влево" },
  { code: ":right:", emoji: "➡️", label: "Вправо" },
  { code: ":arrows_clockwise:", emoji: "🔃", label: "Обновить" },
  { code: ":shuffle:", emoji: "🔀", label: "Перемешать" },
  { code: ":repeat:", emoji: "🔁", label: "Повтор" },
  { code: ":loop:", emoji: "🔂", label: "Цикл" },
  { code: ":back:", emoji: "🔙", label: "Назад" },
  { code: ":soon:", emoji: "🔜", label: "Скоро" },
  { code: ":top:", emoji: "🔝", label: "Топ" },
  { code: ":100:", emoji: "💯", label: "Сто" },
  { code: ":1234:", emoji: "🔢", label: "Цифры" },
  { code: ":hash:", emoji: "#️⃣", label: "Хэштег" },
  { code: ":asterisk:", emoji: "*️⃣", label: "Звёздочка" },
  { code: ":zero:", emoji: "0️⃣", label: "Ноль" },
  { code: ":one:", emoji: "1️⃣", label: "Один" },
  { code: ":two:", emoji: "2️⃣", label: "Два" },
  { code: ":three:", emoji: "3️⃣", label: "Три" },
  { code: ":four:", emoji: "4️⃣", label: "Четыре" },
  { code: ":five:", emoji: "5️⃣", label: "Пять" },
  { code: ":six:", emoji: "6️⃣", label: "Шесть" },
  { code: ":seven:", emoji: "7️⃣", label: "Семь" },
  { code: ":eight:", emoji: "8️⃣", label: "Восемь" },
  { code: ":nine:", emoji: "9️⃣", label: "Девять" },
  { code: ":ten:", emoji: "🔟", label: "Десять" },

  // === ФЛАГИ ===
  { code: ":ru:", emoji: "🇷🇺", label: "Россия" },
  { code: ":us:", emoji: "🇺🇸", label: "США" },
  { code: ":gb:", emoji: "🇬🇧", label: "Британия" },
  { code: ":de:", emoji: "🇩🇪", label: "Германия" },
  { code: ":fr:", emoji: "🇫🇷", label: "Франция" },
  { code: ":it:", emoji: "🇮🇹", label: "Италия" },
  { code: ":es:", emoji: "🇪🇸", label: "Испания" },
  { code: ":jp:", emoji: "🇯🇵", label: "Япония" },
  { code: ":kr:", emoji: "🇰🇷", label: "Корея" },
  { code: ":cn:", emoji: "🇨🇳", label: "Китай" },
  { code: ":in:", emoji: "🇮🇳", label: "Индия" },
  { code: ":br:", emoji: "🇧🇷", label: "Бразилия" },
  { code: ":ca:", emoji: "🇨🇦", label: "Канада" },
  { code: ":au:", emoji: "🇦🇺", label: "Австралия" },
  { code: ":ua:", emoji: "🇺🇦", label: "Украина" },
  { code: ":by:", emoji: "🇧🇾", label: "Беларусь" },
  { code: ":kz:", emoji: "🇰🇿", label: "Казахстан" },
  { code: ":tr:", emoji: "🇹🇷", label: "Турция" },
  { code: ":il:", emoji: "🇮🇱", label: "Израиль" },
  { code: ":ae:", emoji: "🇦🇪", label: "ОАЭ" },
  { code: ":eu:", emoji: "🇪🇺", label: "ЕС" },
  { code: ":un:", emoji: "🇺🇳", label: "ООН" },
  { code: ":pirate:", emoji: "🏴‍☠️", label: "Пират" },
  { code: ":rainbow_flag:", emoji: "🏳️‍🌈", label: "Радуга" },
  { code: ":white_flag:", emoji: "🏳️", label: "Белый флаг" },
  { code: ":black_flag:", emoji: "🏴", label: "Чёрный флаг" },
  { code: ":checkered_flag:", emoji: "🏁", label: "Финиш" },
] as const;

// Парсит :code: в тексте и заменяет на крупные эмодзи
export function renderStickers(text: string): ReactNode[] {
  const parts = text.split(/(:[\w]+:)/g);
  return parts.map((part, i) => {
    const sticker = STICKERS.find((s) => s.code === part);
    if (sticker) {
      return (
        <span key={i} className="inline-block text-3xl align-middle mx-0.5" title={sticker.label}>
          {sticker.emoji}
        </span>
      );
    }
    return part;
  });
}